CREATE INDEX collaborator_FKIndex1 ON collaborator (country_id);
CREATE INDEX collaborator_FKIndex2 ON collaborator (name);
CREATE INDEX collaborator_FKIndex3 ON collaborator (irc);
CREATE INDEX collaborator_FKIndex4 ON collaborator (foundation_date);
CREATE INDEX collaborator_FKIndex5 ON collaborator (create_date);
CREATE INDEX launch_type_FKIndex1 ON launch_type (name);
CREATE INDEX favorite_type_FKIndex1 ON favorite_type (name);
CREATE INDEX currency_FKIndex1 ON currency (name);
CREATE INDEX currency_FKIndex2 ON currency (symbol);
CREATE INDEX currency_FKIndex3 ON currency (code);
CREATE INDEX currency_FKIndex4 ON currency (number);
CREATE INDEX collection_FKIndex1 ON collection (name);
CREATE INDEX collection_wiki_FKIndex1 ON collection_wiki (name);
CREATE INDEX collection_wiki_FKIndex2 ON collection_wiki (url);
CREATE INDEX collection_wiki_FKIndex3 ON collection_wiki (collection_id);
CREATE INDEX collection_wiki_FKIndex4 ON collection_wiki (language_id);

CREATE INDEX collection_alias_FKIndex1 ON collection_alias (name);
CREATE INDEX collection_alias_FKIndex2 ON collection_alias (alias_type_id);
CREATE INDEX collection_alias_FKIndex3 ON collection_alias (collection_id);
CREATE INDEX collection_alias_FKIndex4 ON collection_alias (language_id);
CREATE INDEX plataform_type_FKIndex1 ON plataform_type (name);
CREATE INDEX print_type_FKIndex1 ON print_type (name);
CREATE INDEX image_user_type_FKIndex1 ON image_user_type (name);
CREATE INDEX visual_type_FKIndex1 ON visual_type (name);
CREATE INDEX goods_type_FKIndex1 ON goods_type (name);
CREATE INDEX edition_read_status_type_FKIndex1 ON edition_read_status_type (name);
CREATE INDEX filter_type_FKIndex1 ON filter_type (name);
CREATE INDEX user_filter_type_FKIndex1 ON user_filter_type (name);
CREATE INDEX image_company_type_FKIndex1 ON image_company_type (name);
CREATE INDEX image_collaborator_type_FKIndex1 ON image_collaborator_type (name);
CREATE INDEX lyric_type_FKIndex1 ON lyric_type (name);
CREATE INDEX audio_channels_FKIndex1 ON audio_channels (name);
CREATE INDEX url_type_FKIndex1 ON url_type (name);
CREATE INDEX soundtrack_type_FKIndex1 ON soundtrack_type (name);
CREATE INDEX shops_FKIndex1 ON shops (name);
CREATE INDEX shops_FKIndex2 ON shops (url);
CREATE INDEX compose_type_FKIndex1 ON compose_type (name);
CREATE INDEX archive_container_FKIndex1 ON archive_container (name);
CREATE INDEX based_type_FKIndex1 ON based_type (name);
CREATE INDEX genre_FKIndex1 ON genre (name);
CREATE INDEX media_type_FKIndex1 ON media_type (name);
CREATE INDEX image_soundtrack_type_FKIndex1 ON image_soundtrack_type (name);
CREATE INDEX mod_type_FKIndex1 ON mod_type (name);
CREATE INDEX box_condition_type_FKIndex1 ON box_condition_type (name);
CREATE INDEX condition_type_FKIndex1 ON condition_type (name);
CREATE INDEX company_function_type_FKIndex1 ON company_function_type (name);
CREATE INDEX scale_FKIndex1 ON scale (name);
CREATE INDEX stage_developer_type_FKIndex1 ON stage_developer_type (name);
CREATE INDEX goods_version_FKIndex1 ON goods_version (name);
CREATE INDEX blood_type_FKIndex1 ON blood_type (name);
CREATE INDEX associated_type_FKIndex1 ON associated_type (name);
CREATE INDEX blood_rh_type_FKIndex1 ON blood_rh_type (name);
CREATE INDEX release_ownership_type_FKIndex1 ON release_ownership_type (name);
CREATE INDEX edition_type_FKIndex1 ON edition_type (name);
CREATE INDEX image_audio_type_FKIndex1 ON image_audio_type (name);
CREATE INDEX release_edition_read_status_type_FKIndex1 ON release_edition_read_status_type (name);
CREATE INDEX software_type_FKIndex1 ON software_type (name);
CREATE INDEX ownership_status_FKIndex1 ON ownership_status (name);
CREATE INDEX hash_type_FKIndex1 ON hash_type (name);
CREATE INDEX weapon_type_FKIndex1 ON weapon_type (name);
CREATE INDEX image_goods_type_FKIndex1 ON image_goods_type (name);
CREATE INDEX image_entity_edition_type_FKIndex1 ON image_entity_edition_type (name);
CREATE INDEX create_type_FKIndex1 ON create_type (name);
CREATE INDEX audio_codec_FKIndex1 ON audio_codec (name);
CREATE INDEX audio_codec_FKIndex2 ON audio_codec (lossless);
CREATE INDEX video_codec_FKIndex1 ON video_codec (name);
CREATE INDEX video_codec_FKIndex2 ON video_codec (lossless);
CREATE INDEX material_FKIndex1 ON material (name);
CREATE INDEX product_condition_type_FKIndex1 ON product_condition_type (name);
CREATE INDEX shop_location_FKIndex1 ON shop_location (name);
CREATE INDEX category_FKIndex1 ON category (name);
CREATE INDEX tag_FKIndex1 ON tag (name);
CREATE INDEX release_type_FKIndex1 ON release_type (name);
CREATE INDEX produces_type_FKIndex1 ON produces_type (name);
CREATE INDEX related_type_FKIndex1 ON related_type (name);
CREATE INDEX entity_type_FKIndex1 ON entity_type (name);
CREATE INDEX classification_type_FKIndex1 ON classification_type (name);
CREATE INDEX function_type_FKIndex1 ON function_type (name);
CREATE INDEX collaborator_type_FKIndex1 ON collaborator_type (name);
CREATE INDEX alias_type_FKIndex1 ON alias_type (name);
CREATE INDEX taste_type_FKIndex1 ON taste_type (name);
CREATE INDEX zodiac_sign_FKIndex1 ON zodiac_sign (name);
CREATE INDEX chinese_sign_FKIndex1 ON chinese_sign (name);
CREATE INDEX number_type_FKIndex1 ON number_type (name);
CREATE INDEX spider_item_FKIndex1 ON spider_item (url);
CREATE INDEX spider_item_FKIndex2 ON spider_item (table_name);
CREATE INDEX spider_item_FKIndex3 ON spider_item (complete_crawled);
CREATE INDEX spider_item_FKIndex4 ON spider_item (date);
CREATE INDEX spider_item_FKIndex5 ON spider_item (id);
CREATE INDEX lists_goods_FKIndex1 ON lists_goods (user_id);
CREATE INDEX lists_goods_FKIndex2 ON lists_goods (name);
CREATE INDEX lists_goods_FKIndex3 ON lists_goods (create_date);
CREATE INDEX user_email_FKIndex1 ON user_email (user_id);
CREATE INDEX user_email_FKIndex2 ON user_email (email);
CREATE INDEX company_FKIndex1 ON company (country_id);
CREATE INDEX company_FKIndex2 ON company (name);
CREATE INDEX company_FKIndex3 ON company (website);
CREATE INDEX company_FKIndex4 ON company (foundation_date);
CREATE INDEX company_FKIndex5 ON company (start_year);
CREATE INDEX company_FKIndex6 ON company (social_name);
CREATE INDEX company_FKIndex7 ON company (foundation_date);
CREATE INDEX company_FKIndex8 ON company (create_date);
CREATE INDEX company_alias_FKIndex1 ON company_alias (language_id);
CREATE INDEX company_alias_FKIndex2 ON company_alias (alias_type_id);
CREATE INDEX company_alias_FKIndex3 ON company_alias (company_id);
CREATE INDEX company_alias_FKIndex4 ON company_alias (name);
CREATE INDEX company_alias_FKIndex5 ON company_alias (language_id, name);
CREATE INDEX company_alias_FKIndex6 ON company_alias (name, language_id);
CREATE INDEX collaborator_website_FKIndex1 ON collaborator_website (collaborator_id);
CREATE INDEX collaborator_website_FKIndex2 ON collaborator_website (website);
CREATE INDEX soundtrack_FKIndex1 ON soundtrack (soundtrack_type_id);
CREATE INDEX soundtrack_FKIndex2 ON soundtrack (country_id);
CREATE INDEX soundtrack_FKIndex3 ON soundtrack (launch_year);
CREATE INDEX soundtrack_FKIndex4 ON soundtrack (name);
CREATE INDEX soundtrack_FKIndex5 ON soundtrack (code);
CREATE INDEX social_FKIndex1 ON social (social_type_id);
CREATE INDEX social_FKIndex2 ON social (url);
CREATE INDEX social_type_FKIndex1 ON social_type (name);
CREATE INDEX social_type_FKIndex2 ON social_type (website);
CREATE INDEX social_type_FKIndex3 ON social_type (website_secure);
CREATE INDEX country_FKIndex1 ON country (name);
CREATE INDEX country_FKIndex2 ON country (code);
CREATE INDEX language_FKIndex1 ON language (name);
CREATE INDEX language_FKIndex2 ON language (code);
CREATE INDEX image_FKIndex1 ON image (url);
CREATE INDEX image_FKIndex2 ON image (extension);
CREATE INDEX image_FKIndex3 ON image (name);
CREATE INDEX event_FKIndex1 ON event (country_id);
CREATE INDEX event_FKIndex2 ON event (name);
CREATE INDEX event_FKIndex3 ON event (edition);
CREATE INDEX event_FKIndex4 ON event (location);
CREATE INDEX event_FKIndex5 ON event (website);
CREATE INDEX event_FKIndex6 ON event (date);
CREATE INDEX event_FKIndex7 ON event (duration);
CREATE INDEX event_FKIndex8 ON event (free);
CREATE INDEX version_FKIndex1 ON version (stage_developer_type_id);
CREATE INDEX version_FKIndex2 ON version (number);
CREATE INDEX requirements_FKIndex1 ON requirements (version_id);
CREATE INDEX requirements_FKIndex2 ON requirements (video_board);
CREATE INDEX requirements_FKIndex3 ON requirements (processor);
CREATE INDEX requirements_FKIndex4 ON requirements (memory);
CREATE INDEX requirements_FKIndex5 ON requirements (hd_storage);
CREATE INDEX user_filter_FKIndex1 ON user_filter (user_id);
CREATE INDEX user_filter_FKIndex2 ON user_filter (user_filter_type_id);
CREATE INDEX user_filter_FKIndex3 ON user_filter (name);
CREATE INDEX people_FKIndex1 ON people (blood_type_id);
CREATE INDEX people_FKIndex2 ON people (blood_rh_type_id);
CREATE INDEX people_FKIndex3 ON people (country_id);
CREATE INDEX people_FKIndex4 ON people (gender);
CREATE INDEX people_FKIndex5 ON people (website);
CREATE INDEX people_FKIndex6 ON people (birth_place);
CREATE INDEX people_FKIndex7 ON people (birth_date);
CREATE INDEX users_FKIndex1 ON users (username);
CREATE INDEX users_FKIndex2 ON users (pass);
CREATE INDEX users_FKIndex3 ON users (gender);
CREATE INDEX users_FKIndex4 ON users (location);
CREATE INDEX users_FKIndex5 ON users (birthday);
CREATE INDEX users_FKIndex6 ON users (signup_date);
CREATE INDEX users_FKIndex7 ON users (activated);
CREATE INDEX users_has_social_FKIndex1 ON users_has_social (user_id);
CREATE INDEX users_has_social_FKIndex2 ON users_has_social (social_id);
CREATE INDEX users_has_social_FKIndex3 ON users_has_social (last_checked);
CREATE INDEX users_has_social_FKIndex4 ON users_has_social (create_date);
CREATE INDEX tag_has_filter_type_FKIndex1 ON tag_has_filter_type (filter_type_id);
CREATE INDEX tag_has_filter_type_FKIndex2 ON tag_has_filter_type (tag_id);
CREATE INDEX people_has_social_FKIndex1 ON people_has_social (social_id);
CREATE INDEX people_has_social_FKIndex2 ON people_has_social (people_id);
CREATE INDEX people_has_social_FKIndex3 ON people_has_social (last_checked);
CREATE INDEX people_has_social_FKIndex4 ON people_has_social (create_date);
CREATE INDEX collaborator_has_social_FKIndex1 ON collaborator_has_social (social_id);
CREATE INDEX collaborator_has_social_FKIndex2 ON collaborator_has_social (collaborator_id);
CREATE INDEX collaborator_has_social_FKIndex3 ON collaborator_has_social (last_checked);
CREATE INDEX collaborator_has_social_FKIndex4 ON collaborator_has_social (create_date);
CREATE INDEX shops_has_country_FKIndex1 ON shops_operate_on_country (shops_id);
CREATE INDEX shops_has_country_FKIndex2 ON shops_operate_on_country (country_id);
CREATE INDEX people_nacionalization_on_country_FKIndex1 ON people_nacionalization_on_country (people_id);
CREATE INDEX people_nacionalization_on_country_FKIndex2 ON people_nacionalization_on_country (country_id);
CREATE INDEX country_has_language_FKIndex1 ON country_has_language (language_id);
CREATE INDEX country_has_language_FKIndex2 ON country_has_language (country_id);
CREATE INDEX collaborator_member_FKIndex1 ON collaborator_member (name);
CREATE INDEX collaborator_member_FKIndex2 ON collaborator_member (active);
CREATE INDEX collaborator_has_collaborator_member_FKIndex1 ON collaborator_has_collaborator_member (collaborator_id);
CREATE INDEX collaborator_has_collaborator_member_FKIndex2 ON collaborator_has_collaborator_member (collaborator_member_id);
CREATE INDEX collaborator_has_collaborator_member_FKIndex3 ON collaborator_has_collaborator_member (founder);
CREATE INDEX soundtrack_integrate_collection_FKIndex1 ON soundtrack_integrate_collection (collection_id);
CREATE INDEX soundtrack_integrate_collection_FKIndex2 ON soundtrack_integrate_collection (soundtrack_id);
CREATE INDEX category_has_filter_type_FKIndex1 ON category_has_filter_type (category_id);
CREATE INDEX category_has_filter_type_FKIndex2 ON category_has_filter_type (filter_type_id);
CREATE INDEX genre_has_filter_type_FKIndex1 ON genre_has_filter_type (genre_id);
CREATE INDEX genre_has_filter_type_FKIndex2 ON genre_has_filter_type (filter_type_id);
CREATE INDEX audio_FKIndex1 ON audio (audio_codec_id);
CREATE INDEX audio_FKIndex2 ON audio (country_id);
CREATE INDEX audio_FKIndex3 ON audio (audio_channels_id);
CREATE INDEX audio_FKIndex4 ON audio (name);
CREATE INDEX audio_FKIndex5 ON audio (duration);
CREATE INDEX audio_FKIndex6 ON audio (bitrate);
CREATE INDEX audio_has_language_FKIndex1 ON audio_has_language (audio_id);
CREATE INDEX audio_has_language_FKIndex2 ON audio_has_language (language_id);
CREATE INDEX company_sponsors_event_FKIndex1 ON company_sponsors_event (company_id);
CREATE INDEX company_sponsors_event_FKIndex2 ON company_sponsors_event (event_id);
CREATE INDEX country_has_currency_FKIndex1 ON country_has_currency (currency_id);
CREATE INDEX country_has_currency_FKIndex2 ON country_has_currency (country_id);
CREATE INDEX country_has_currency_FKIndex3 ON country_has_currency (main);
CREATE INDEX company_owner_collection_FKIndex1 ON company_owner_collection (company_id);
CREATE INDEX company_owner_collection_FKIndex2 ON company_owner_collection (collection_id);
CREATE INDEX company_has_country_FKIndex1 ON company_has_country (country_id);
CREATE INDEX company_has_country_FKIndex2 ON company_has_country (company_id);
CREATE INDEX company_has_social_FKIndex1 ON company_has_social (social_id);
CREATE INDEX company_has_social_FKIndex2 ON company_has_social (company_id);
CREATE INDEX company_has_social_FKIndex3 ON company_has_social (last_checked);
CREATE INDEX company_has_social_FKIndex4 ON company_has_social (create_date);
CREATE INDEX people_has_image_FKIndex1 ON people_has_image (image_id);
CREATE INDEX people_has_image_FKIndex2 ON people_has_image (people_id);
CREATE INDEX lists_edition_FKIndex1 ON lists_edition (user_id);
CREATE INDEX lists_edition_FKIndex2 ON lists_edition (entity_type_id);
CREATE INDEX lists_edition_FKIndex3 ON lists_edition (name);
CREATE INDEX lists_edition_FKIndex4 ON lists_edition (create_date);
CREATE INDEX lists_release_FKIndex1 ON lists_release (user_id);
CREATE INDEX lists_release_FKIndex2 ON lists_release (entity_type_id);
CREATE INDEX lists_release_FKIndex3 ON lists_release (name);
CREATE INDEX lists_release_FKIndex4 ON lists_release (create_date);
CREATE INDEX audio_has_genre_FKIndex1 ON audio_has_genre (genre_id);
CREATE INDEX audio_has_genre_FKIndex2 ON audio_has_genre (audio_id);
CREATE INDEX soundtrack_has_image_FKIndex1 ON soundtrack_has_image (soundtrack_id);
CREATE INDEX soundtrack_has_image_FKIndex2 ON soundtrack_has_image (image_id);
CREATE INDEX soundtrack_has_image_FKIndex3 ON soundtrack_has_image (image_soundtrack_type_id);
CREATE INDEX lyric_FKIndex1 ON lyric (language_id);
CREATE INDEX lyric_FKIndex2 ON lyric (audio_id);
CREATE INDEX lyric_FKIndex3 ON lyric (user_id);
CREATE INDEX lyric_FKIndex4 ON lyric (lyric_type_id);
CREATE INDEX lyric_FKIndex5 ON lyric (title);
CREATE INDEX entity_FKIndex1 ON entity (country_id);
CREATE INDEX entity_FKIndex2 ON entity (language_id);
CREATE INDEX entity_FKIndex3 ON entity (collection_id);
CREATE INDEX entity_FKIndex4 ON entity (classification_type_id);
CREATE INDEX entity_FKIndex5 ON entity (entity_type_id);
CREATE INDEX entity_FKIndex6 ON entity (launch_year);
CREATE INDEX entity_FKIndex7 ON entity (collection_started);
CREATE INDEX entity_FKIndex8 ON entity (collection_started, id);
CREATE INDEX entity_description_FKIndex1 ON entity_description (entity_id);
CREATE INDEX entity_description_FKIndex2 ON entity_description (language_id);
CREATE INDEX entity_wiki_FKIndex1 ON entity_wiki (entity_id);
CREATE INDEX entity_wiki_FKIndex2 ON entity_wiki (language_id);
CREATE INDEX entity_wiki_FKIndex3 ON entity_wiki (name);
CREATE INDEX entity_wiki_FKIndex4 ON entity_wiki (url);
CREATE INDEX archive_FKIndex1 ON archive (version_id);
CREATE INDEX archive_FKIndex2 ON archive (name);
CREATE INDEX archive_FKIndex3 ON archive (size);
CREATE INDEX archive_FKIndex4 ON archive (extension);
CREATE INDEX entity_synopsis_FKIndex1 ON entity_synopsis (entity_id);
CREATE INDEX entity_synopsis_FKIndex2 ON entity_synopsis (language_id);
CREATE INDEX people_alias_FKIndex1 ON people_alias (people_id);
CREATE INDEX people_alias_FKIndex2 ON people_alias (alias_type_id);
CREATE INDEX people_alias_FKIndex3 ON people_alias (name);
CREATE INDEX people_alias_FKIndex4 ON people_alias (lastname);
CREATE INDEX people_alias_FKIndex5 ON people_alias (name, lastname);
CREATE INDEX persona_weakness_FKIndex1 ON persona_weakness (name);
CREATE INDEX persona_weakness_FKIndex2 ON persona_weakness (persona_id);
CREATE INDEX persona_power_FKIndex1 ON persona_power (name);
CREATE INDEX persona_power_FKIndex2 ON persona_power (persona_id);
CREATE INDEX persona_element_FKIndex1 ON persona_element (name);
CREATE INDEX persona_element_FKIndex2 ON persona_element (persona_id);
CREATE INDEX persona_favorite_FKIndex1 ON persona_favorite (name);
CREATE INDEX persona_favorite_FKIndex2 ON persona_favorite (persona_id);
CREATE INDEX persona_favorite_FKIndex3 ON persona_favorite (favorite_type_id);
CREATE INDEX persona_taste_FKIndex1 ON persona_taste (name);
CREATE INDEX persona_taste_FKIndex2 ON persona_taste (persona_id);
CREATE INDEX persona_taste_FKIndex3 ON persona_taste (taste_type_id);
CREATE INDEX persona_weapon_FKIndex1 ON persona_weapon (name);
CREATE INDEX persona_weapon_FKIndex2 ON persona_weapon (persona_id);
CREATE INDEX persona_weapon_FKIndex3 ON persona_weapon (weapon_type_id);
CREATE INDEX persona_FKIndex1 ON persona (blood_type_id);
CREATE INDEX persona_FKIndex2 ON persona (blood_rh_type_id);
CREATE INDEX persona_FKIndex3 ON persona (gender);
CREATE INDEX persona_FKIndex4 ON persona (birthday);
CREATE INDEX persona_FKIndex5 ON persona (height);
CREATE INDEX persona_FKIndex6 ON persona (weight);
CREATE INDEX persona_FKIndex7 ON persona (eyes_color);
CREATE INDEX persona_FKIndex8 ON persona (hair_color);
CREATE INDEX persona_FKIndex9 ON persona (exact_hair_color);
CREATE INDEX persona_FKIndex10 ON persona (hair_lenght);
CREATE INDEX persona_FKIndex11 ON persona (age);
CREATE INDEX persona_FKIndex12 ON persona (birthyear);
CREATE INDEX persona_FKIndex13 ON persona (bust_size);
CREATE INDEX persona_FKIndex14 ON persona (waist_size);
CREATE INDEX persona_FKIndex15 ON persona (butt_size);
CREATE INDEX persona_FKIndex16 ON persona (element);
CREATE INDEX persona_FKIndex17 ON persona (apparent_age);
CREATE INDEX persona_FKIndex18 ON persona (chinese_sign_id);
CREATE INDEX persona_FKIndex19 ON persona (zodiac_sign_id);
CREATE INDEX goods_launch_country_FKIndex1 ON goods_launch_country (country_id);
CREATE INDEX goods_launch_country_FKIndex2 ON goods_launch_country (goods_id);
CREATE INDEX goods_launch_country_FKIndex3 ON goods_launch_country (currency_id);
CREATE INDEX goods_launch_country_FKIndex4 ON goods_launch_country (launch_date);
CREATE INDEX goods_launch_country_FKIndex5 ON goods_launch_country (launch_type_id);
CREATE INDEX goods_launch_country_FKIndex6 ON goods_launch_country (launch_price);
CREATE INDEX goods_has_goods_version_FKIndex1 ON goods_has_goods_version (goods_version_id);
CREATE INDEX goods_has_goods_version_FKIndex2 ON goods_has_goods_version (goods_id);

CREATE INDEX soundtrack_has_audio_FKIndex1 ON soundtrack_has_audio (soundtrack_id);
CREATE INDEX soundtrack_has_audio_FKIndex2 ON soundtrack_has_audio (audio_id);
CREATE INDEX entity_has_category_FKIndex1 ON entity_has_category (entity_id);
CREATE INDEX entity_has_category_FKIndex2 ON entity_has_category (category_id);
CREATE INDEX entity_has_tag_FKIndex1 ON entity_has_tag (tag_id);
CREATE INDEX entity_has_tag_FKIndex2 ON entity_has_tag (entity_id);
CREATE INDEX entity_has_genre_FKIndex1 ON entity_has_genre (genre_id);
CREATE INDEX entity_has_genre_FKIndex2 ON entity_has_genre (entity_id);
CREATE INDEX hash_FKIndex1 ON hash (archive_id);
CREATE INDEX hash_FKIndex2 ON hash (hash_type_id);
CREATE INDEX hash_FKIndex3 ON hash (create_date);
CREATE INDEX persona_related_persona_FKIndex1 ON persona_related_persona (persona_id);
CREATE INDEX persona_related_persona_FKIndex2 ON persona_related_persona (another_persona_id);
CREATE INDEX persona_related_persona_FKIndex3 ON persona_related_persona (related_type_id);
CREATE INDEX entity_based_entity_FKIndex1 ON entity_based_entity (entity_id);
CREATE INDEX entity_based_entity_FKIndex2 ON entity_based_entity (another_entity_id);
CREATE INDEX entity_based_entity_FKIndex3 ON entity_based_entity (based_type_id);
CREATE INDEX entity_alias_FKIndex1 ON entity_alias (language_id);
CREATE INDEX entity_alias_FKIndex2 ON entity_alias (entity_id);
CREATE INDEX entity_alias_FKIndex3 ON entity_alias (alias_type_id);
CREATE INDEX entity_alias_FKIndex4 ON entity_alias (name);
CREATE INDEX entity_edition_FKIndex1 ON entity_edition (entity_id);
CREATE INDEX entity_edition_FKIndex2 ON entity_edition (event_id);
CREATE INDEX entity_edition_FKIndex3 ON entity_edition (edition_type_id);
CREATE INDEX entity_edition_FKIndex4 ON entity_edition (title);
CREATE INDEX entity_edition_FKIndex5 ON entity_edition (subtitle);
CREATE INDEX entity_edition_FKIndex6 ON entity_edition (free);
CREATE INDEX entity_edition_FKIndex7 ON entity_edition (censored);
CREATE INDEX entity_edition_FKIndex8 ON entity_edition (code);
CREATE INDEX entity_edition_FKIndex9 ON entity_edition (complement_code);
CREATE INDEX entity_edition_FKIndex10 ON entity_edition (height);
CREATE INDEX entity_edition_FKIndex11 ON entity_edition (width);
CREATE INDEX entity_edition_FKIndex12 ON entity_edition (depth);
CREATE INDEX entity_edition_FKIndex13 ON entity_edition (weight);
CREATE INDEX entity_release_FKIndex1 ON entity_release (entity_edition_id);
CREATE INDEX entity_release_FKIndex2 ON entity_release (country_id);
CREATE INDEX entity_release_FKIndex3 ON entity_release (release_type_id);
CREATE INDEX entity_release_FKIndex4 ON entity_release (entity_id);
CREATE INDEX entity_release_FKIndex5 ON entity_release (release_date);
CREATE INDEX people_compose_audio_FKIndex1 ON people_compose_audio (audio_id);
CREATE INDEX people_compose_audio_FKIndex2 ON people_compose_audio (people_id);
CREATE INDEX people_compose_audio_FKIndex3 ON people_compose_audio (compose_type_id);
CREATE INDEX people_compose_audio_FKIndex4 ON people_compose_audio (people_alias_id);
CREATE INDEX people_produces_entity_FKIndex1 ON people_produces_entity (people_id);
CREATE INDEX people_produces_entity_FKIndex2 ON people_produces_entity (entity_id);
CREATE INDEX people_produces_entity_FKIndex3 ON people_produces_entity (produces_type_id);
CREATE INDEX people_produces_entity_FKIndex4 ON people_produces_entity (people_alias_id);
CREATE INDEX goods_FKIndex1 ON goods (collection_id);
CREATE INDEX goods_FKIndex2 ON goods (goods_type_id);
CREATE INDEX goods_FKIndex3 ON goods (height);
CREATE INDEX goods_FKIndex4 ON goods (width);
CREATE INDEX goods_FKIndex5 ON goods (weight);
CREATE INDEX goods_FKIndex6 ON goods (has_counterfeit);
CREATE INDEX goods_FKIndex7 ON goods (collection_started);
CREATE INDEX goods_FKIndex8 ON goods (draft);
CREATE INDEX goods_FKIndex9 ON goods (length);
CREATE INDEX lists_edition_list_entity_edition_FKIndex1 ON lists_edition_list_entity_edition (lists_edition_id);
CREATE INDEX lists_edition_list_entity_edition_FKIndex2 ON lists_edition_list_entity_edition (entity_edition_id);
CREATE INDEX lists_edition_list_entity_edition_FKIndex3 ON lists_edition_list_entity_edition (edition_read_status_type_id);
CREATE INDEX lists_edition_list_entity_edition_FKIndex4 ON lists_edition_list_entity_edition (condition_type_id);
CREATE INDEX lists_edition_list_entity_edition_FKIndex5 ON lists_edition_list_entity_edition (ownership_status_id);
CREATE INDEX  lists_goods_list_goods_FKIndex1 ON lists_goods_list_goods (lists_goods_id);
CREATE INDEX  lists_goods_list_goods_FKIndex2 ON lists_goods_list_goods (goods_id);
CREATE INDEX  lists_goods_list_goods_FKIndex3 ON lists_goods_list_goods (product_condition_type_id);
CREATE INDEX  lists_goods_list_goods_FKIndex4 ON lists_goods_list_goods (box_condition_type_id);
CREATE INDEX  lists_goods_list_goods_FKIndex5 ON lists_goods_list_goods (ownership_status_id);
CREATE INDEX persona_unusual_features_FKIndex1 ON persona_unusual_features (persona_id);
CREATE INDEX persona_unusual_features_FKIndex2 ON persona_unusual_features (name);
CREATE INDEX persona_alias_FKIndex1 ON persona_alias(persona_id);
CREATE INDEX persona_alias_FKIndex2 ON persona_alias(alias_type_id);
CREATE INDEX persona_alias_FKIndex3 ON persona_alias(name);
CREATE INDEX persona_alias_FKIndex4 ON persona_alias(last_name);
CREATE INDEX persona_alias_FKIndex5 ON persona_alias(name, last_name);
CREATE INDEX persona_occupation_FKIndex1 ON persona_occupation(persona_id);
CREATE INDEX persona_occupation_FKIndex2 ON persona_occupation(occupation);
CREATE INDEX persona_affiliation_FKIndex1 ON persona_affiliation(persona_id);
CREATE INDEX persona_affiliation_FKIndex2 ON persona_affiliation(name);
CREATE INDEX persona_race_FKIndex1 ON persona_race(persona_id);
CREATE INDEX persona_race_FKIndex2 ON persona_race(name);
CREATE INDEX game_release_FKIndex1 ON game_release (entity_release_id);
CREATE INDEX game_release_FKIndex2 ON game_release (emulate);
CREATE INDEX software_edition_FKIndex1 ON software_edition (entity_edition_id);
CREATE INDEX software_edition_FKIndex2 ON software_edition (media_type_id);
CREATE INDEX software_edition_FKIndex3 ON software_edition (software_type_id);
CREATE INDEX software_edition_FKIndex4 ON software_edition (plataform_type_id);
CREATE INDEX software_edition_FKIndex5 ON software_edition (visual_type_id);
CREATE INDEX software_edition_has_version_FKIndex1 ON software_edition_has_version (software_edition_id);
CREATE INDEX software_edition_has_version_FKIndex2 ON software_edition_has_version (version_id);
CREATE INDEX read_edition_FKIndex1 ON read_edition (entity_edition_id);
CREATE INDEX read_edition_FKIndex2 ON read_edition (print_type_id);
CREATE INDEX read_edition_FKIndex3 ON read_edition (pages_number);
CREATE INDEX read_edition_FKIndex4 ON read_edition (chapters_number);
CREATE INDEX soundtrack_for_entity_edition_FKIndex1 ON soundtrack_for_entity_edition (soundtrack_id);
CREATE INDEX soundtrack_for_entity_edition_FKIndex2 ON soundtrack_for_entity_edition (entity_edition_id);
CREATE INDEX entity_edition_launch_country_FKIndex1 ON entity_edition_launch_country (entity_edition_id);
CREATE INDEX entity_edition_launch_country_FKIndex2 ON entity_edition_launch_country (country_id);
CREATE INDEX entity_edition_launch_country_FKIndex3 ON entity_edition_launch_country (currency_id);
CREATE INDEX entity_edition_launch_country_FKIndex4 ON entity_edition_launch_country (launch_date);
CREATE INDEX entity_edition_launch_country_FKIndex5 ON entity_edition_launch_country (launch_price);
CREATE INDEX entity_edition_has_subtitle_FKIndex1 ON entity_edition_has_subtitle (subtitle_id);
CREATE INDEX entity_edition_has_subtitle_FKIndex2 ON entity_edition_has_subtitle (entity_edition_id);
CREATE INDEX entity_edition_has_language_FKIndex1 ON entity_edition_has_language (entity_edition_id);
CREATE INDEX entity_edition_has_language_FKIndex2 ON entity_edition_has_language (language_id);
CREATE INDEX entity_release_has_version_FKIndex1 ON entity_release_has_version (entity_release_id);
CREATE INDEX entity_release_has_version_FKIndex2 ON entity_release_has_version (version_id);
CREATE INDEX entity_release_has_language_FKIndex1 ON entity_release_has_language (entity_release_id);
CREATE INDEX entity_release_has_language_FKIndex2 ON entity_release_has_language (language_id);
CREATE INDEX mod_release_FKIndex1 ON mod_release (mod_type_id);
CREATE INDEX mod_release_FKIndex2 ON mod_release (entity_release_id);
CREATE INDEX mod_release_FKIndex3 ON mod_release (name);
CREATE INDEX mod_release_FKIndex4 ON mod_release (author);
CREATE INDEX mod_release_FKIndex5 ON mod_release (launch_date);
CREATE INDEX mod_release_has_image_FKIndex1 ON mod_release_has_image (mod_release_id);
CREATE INDEX mod_release_has_image_FKIndex2 ON mod_release_has_image (image_id);
CREATE INDEX collaborator_provides_entity_release_FKIndex1 ON collaborator_provides_entity_release(collaborator_id);
CREATE INDEX collaborator_provides_entity_release_FKIndex2 ON collaborator_provides_entity_release(entity_release_id);
CREATE INDEX collaborator_provides_entity_release_FKIndex3 ON collaborator_provides_entity_release(collaborator_type_id);
CREATE INDEX collaborator_member_produces_entity_release_FKIndex1 ON collaborator_member_produces_entity_release (collaborator_member_id);
CREATE INDEX collaborator_member_produces_entity_release_FKIndex2 ON collaborator_member_produces_entity_release (entity_release_id);
CREATE INDEX collaborator_member_produces_entity_release_FKIndex3 ON collaborator_member_produces_entity_release (collaborator_member_type_id);
CREATE INDEX entity_edition_has_company_FKIndex1 ON entity_edition_has_company (company_id);
CREATE INDEX entity_edition_has_company_FKIndex2 ON entity_edition_has_company (entity_edition_id);
CREATE INDEX entity_edition_has_company_FKIndex3 ON entity_edition_has_company (company_function_type_id);
CREATE INDEX entity_has_company_FKIndex1 ON entity_has_company(company_id);
CREATE INDEX entity_has_company_FKIndex2 ON entity_has_company(company_function_type_id);
CREATE INDEX entity_has_company_FKIndex3 ON entity_has_company(entity_id);
CREATE INDEX entity_edition_has_image_FKIndex1 ON entity_edition_has_image (image_id);
CREATE INDEX entity_edition_has_image_FKIndex2 ON entity_edition_has_image (entity_edition_id);
CREATE INDEX entity_edition_has_image_FKIndex3 ON entity_edition_has_image (image_entity_edition_type_id);
CREATE INDEX entity_has_image_FKIndex1 ON entity_has_image (image_id);
CREATE INDEX entity_has_image_FKIndex2 ON entity_has_image (entity_id);
CREATE INDEX number_edition_FKIndex1 ON number_edition (number_type_id);
CREATE INDEX number_edition_FKIndex2 ON number_edition (entity_edition_id);
CREATE INDEX number_edition_FKIndex3 ON number_edition (number);
CREATE INDEX number_release_FKIndex1 ON number_release (number_type_id);
CREATE INDEX number_release_FKIndex2 ON number_release (entity_release_id);
CREATE INDEX number_release_FKIndex3 ON number_release (number_release_id);
CREATE INDEX number_release_FKIndex4 ON number_release (number);
CREATE INDEX lists_release_list_entity_release_FKIndex1 ON lists_release_list_entity_release (lists_release_id);
CREATE INDEX lists_release_list_entity_release_FKIndex2 ON lists_release_list_entity_release (entity_release_id);
CREATE INDEX lists_release_list_entity_release_FKIndex3 ON lists_release_list_entity_release (release_ownership_type_id);
CREATE INDEX lists_release_list_entity_release_FKIndex4 ON lists_release_list_entity_release (release_edition_read_status_type_id);
CREATE INDEX lists_release_list_entity_release_FKIndex5 ON lists_release_list_entity_release (local_storage);
CREATE INDEX persona_comments_FKIndex1 ON persona_comments(user_id);
CREATE INDEX persona_comments_FKIndex2 ON persona_comments(persona_id);
CREATE INDEX persona_comments_FKIndex3 ON persona_comments(title);
CREATE INDEX persona_comments_FKIndex4 ON persona_comments(create_date);
CREATE INDEX persona_comments_FKIndex5 ON persona_comments(update_date);
CREATE INDEX soundtrack_comments_FKIndex1 ON soundtrack_comments(user_id);
CREATE INDEX soundtrack_comments_FKIndex2 ON soundtrack_comments(soundtrack_id);
CREATE INDEX soundtrack_comments_FKIndex3 ON soundtrack_comments(title);
CREATE INDEX soundtrack_comments_FKIndex4 ON soundtrack_comments(create_date);
CREATE INDEX soundtrack_comments_FKIndex5 ON soundtrack_comments(update_date);
CREATE INDEX audio_comments_FKIndex1 ON audio_comments(user_id);
CREATE INDEX audio_comments_FKIndex2 ON audio_comments(audio_id);
CREATE INDEX audio_comments_FKIndex3 ON audio_comments(title);
CREATE INDEX audio_comments_FKIndex4 ON audio_comments(create_date);
CREATE INDEX audio_comments_FKIndex5 ON audio_comments(update_date);
CREATE INDEX company_comments_FKIndex1 ON company_comments(user_id);
CREATE INDEX company_comments_FKIndex2 ON company_comments(company_id);
CREATE INDEX company_comments_FKIndex3 ON company_comments(title);
CREATE INDEX company_comments_FKIndex4 ON company_comments(create_date);
CREATE INDEX company_comments_FKIndex5 ON company_comments(update_date);
CREATE INDEX people_comments_FKIndex1 ON people_comments(user_id);
CREATE INDEX people_comments_FKIndex2 ON people_comments(people_id);
CREATE INDEX people_comments_FKIndex3 ON people_comments(title);
CREATE INDEX people_comments_FKIndex4 ON people_comments(create_date);
CREATE INDEX people_comments_FKIndex5 ON people_comments(update_date);
CREATE INDEX goods_comments_FKIndex1 ON goods_comments(user_id);
CREATE INDEX goods_comments_FKIndex2 ON goods_comments(goods_id);
CREATE INDEX goods_comments_FKIndex3 ON goods_comments(title);
CREATE INDEX goods_comments_FKIndex4 ON goods_comments(create_date);
CREATE INDEX goods_comments_FKIndex5 ON goods_comments(update_date);
CREATE INDEX collaborator_comments_FKIndex1 ON collaborator_comments(user_id);
CREATE INDEX collaborator_comments_FKIndex2 ON collaborator_comments(collaborator_id);
CREATE INDEX collaborator_comments_FKIndex3 ON collaborator_comments(title);
CREATE INDEX collaborator_comments_FKIndex4 ON collaborator_comments(create_date);
CREATE INDEX collaborator_comments_FKIndex5 ON collaborator_comments(update_date);
CREATE INDEX entity_comments_FKIndex1 ON entity_comments(user_id);
CREATE INDEX entity_comments_FKIndex2 ON entity_comments(entity_id);
CREATE INDEX entity_comments_FKIndex3 ON entity_comments(title);
CREATE INDEX entity_comments_FKIndex4 ON entity_comments(create_date);
CREATE INDEX entity_comments_FKIndex5 ON entity_comments(update_date);
CREATE INDEX entity_release_comments_FKIndex1 ON entity_release_comments(user_id);
CREATE INDEX entity_release_comments_FKIndex2 ON entity_release_comments(entity_release_id);
CREATE INDEX entity_release_comments_FKIndex3 ON entity_release_comments(title);
CREATE INDEX entity_release_comments_FKIndex4 ON entity_release_comments(create_date);
CREATE INDEX entity_release_comments_FKIndex5 ON entity_release_comments(update_date);
CREATE INDEX entity_edition_comments_FKIndex1 ON entity_edition_comments(user_id);
CREATE INDEX entity_edition_comments_FKIndex2 ON entity_edition_comments(entity_edition_id);
CREATE INDEX entity_edition_comments_FKIndex3 ON entity_edition_comments(title);
CREATE INDEX entity_edition_comments_FKIndex4 ON entity_edition_comments(create_date);
CREATE INDEX entity_edition_comments_FKIndex5 ON entity_edition_comments(update_date);
CREATE INDEX entity_release_comments_FKIndex1 ON entity_release_comments(user_id);
CREATE INDEX entity_release_comments_FKIndex2 ON entity_release_comments(entity_release_id);
CREATE INDEX collection_comments_FKIndex1 ON collection_comments(user_id);
CREATE INDEX collection_comments_FKIndex2 ON collection_comments(collection_id);
CREATE INDEX collection_comments_FKIndex3 ON collection_comments(title);
CREATE INDEX collection_comments_FKIndex4 ON collection_comments(create_date);
CREATE INDEX collection_comments_FKIndex5 ON collection_comments(update_date);
CREATE INDEX people_voice_persona_FKIndex1 ON people_voice_persona(persona_id);
CREATE INDEX people_voice_persona_FKIndex2 ON people_voice_persona(people_id);
CREATE INDEX people_voice_persona_FKIndex3 ON people_voice_persona(language_id);
CREATE INDEX people_voice_persona_FKIndex4 ON people_voice_persona(entity_edition_id);
CREATE INDEX people_voice_persona_FKIndex5 ON people_voice_persona(entity_id);
CREATE INDEX tag_user_filter_FKIndex1 ON tag_user_filter(user_filter_id);
CREATE INDEX tag_user_filter_FKIndex2 ON tag_user_filter(tag_id); 
CREATE INDEX classification_user_filter_FKIndex1 ON classification_user_filter(user_filter_id);
CREATE INDEX classification_user_filter_FKIndex2 ON classification_user_filter(classification_id);
CREATE INDEX category_user_filter_FKIndex1 ON category_user_filter(user_filter_id);
CREATE INDEX category_user_filter_FKIndex2 ON category_user_filter(category_id);
CREATE INDEX persona_appear_on_entity_FKIndex1 ON persona_appear_on_entity(persona_id);
CREATE INDEX persona_appear_on_entity_FKIndex2 ON persona_appear_on_entity(entity_id);
CREATE INDEX persona_appear_on_entity_FKIndex3 ON persona_appear_on_entity(persona_alias_id);
CREATE INDEX persona_appear_on_entity_FKIndex4 ON persona_appear_on_entity(first_appear);
CREATE INDEX persona_has_tag_FKIndex1 ON persona_has_tag(tag_id);
CREATE INDEX persona_has_tag_FKIndex2 ON persona_has_tag(persona_id);
CREATE INDEX persona_has_image_FKIndex1 ON persona_has_image(image_id);
CREATE INDEX persona_has_image_FKIndex2 ON persona_has_image(persona_id);
CREATE INDEX company_has_image_FKIndex1 ON company_has_image(image_id);
CREATE INDEX company_has_image_FKIndex2 ON company_has_image(company_id);
CREATE INDEX company_has_image_FKIndex3 ON company_has_image(image_company_type_id);
CREATE INDEX audio_has_image_FKIndex1 ON audio_has_image(image_id);
CREATE INDEX audio_has_image_FKIndex2 ON audio_has_image(audio_id);
CREATE INDEX audio_has_image_FKIndex3 ON audio_has_image(image_audio_type_id);
CREATE INDEX collaborator_has_image_FKIndex1 ON collaborator_has_image(image_id);
CREATE INDEX collaborator_has_image_FKIndex2 ON collaborator_has_image(collaborator_id);
CREATE INDEX collaborator_has_image_FKIndex3 ON collaborator_has_image(image_collaborator_type_id);
CREATE INDEX user_has_image_FKIndex1 ON user_has_image(image_id);
CREATE INDEX user_has_image_FKIndex2 ON user_has_image(user_id);
CREATE INDEX user_has_image_FKIndex3 ON user_has_image(image_user_type_id);
CREATE INDEX people_voice_persona_has_number_edition_FKIndex1 ON people_voice_persona_on_number_edition(people_voice_persona_persona_id, people_voice_persona_people_id, people_voice_persona_language_id);
CREATE INDEX people_voice_persona_has_number_edition_FKIndex2 ON people_voice_persona_on_number_edition(people_voice_persona_language_id);
CREATE INDEX people_voice_persona_has_number_edition_FKIndex3 ON people_voice_persona_on_number_edition(people_voice_persona_people_id);
CREATE INDEX people_voice_persona_has_number_edition_FKIndex4 ON people_voice_persona_on_number_edition(people_voice_persona_persona_id);
CREATE INDEX people_voice_persona_has_number_edition_FKIndex5 ON people_voice_persona_on_number_edition(number_edition_id);
CREATE INDEX requirements_has_driver_FKIndex1 ON requirements_has_driver(requirements_id);
CREATE INDEX requirements_has_driver_FKIndex2 ON requirements_has_driver(driver_id);
CREATE INDEX driver_FKIndex1 ON driver (name);
CREATE INDEX driver_FKIndex2 ON driver (url_download);
CREATE INDEX archive_url_FKIndex1 ON archive_url (archive_id);
CREATE INDEX archive_url_FKIndex2 ON archive_url (url_type_id);
CREATE INDEX archive_url_FKIndex3 ON archive_url (url);
CREATE INDEX video_release_FKIndex1 ON video_release(entity_release_id);
CREATE INDEX video_release_FKIndex2 ON video_release(archive_container_id);
CREATE INDEX video_release_FKIndex3 ON video_release(video_codec_id);
CREATE INDEX video_release_FKIndex4 ON video_release(duration);
CREATE INDEX video_release_FKIndex5 ON video_release(resolution);
CREATE INDEX video_release_FKIndex6 ON video_release(softsub);
CREATE INDEX video_release_has_audio_codec_FKIndex1 ON video_release_has_audio_codec(audio_codec_id);
CREATE INDEX video_release_has_audio_codec_FKIndex2 ON video_release_has_audio_codec(video_release_entity_release_id);
CREATE INDEX video_release_has_audio_codec_FKIndex3 ON video_release_has_audio_codec(language_id);
CREATE INDEX goods_has_tag_FKIndex1 ON goods_has_tag (tag_id);
CREATE INDEX goods_has_tag_FKIndex2 ON goods_has_tag (goods_id);
CREATE INDEX goods_has_shops_FKIndex1 ON goods_has_shops (goods_id);
CREATE INDEX goods_has_shops_FKIndex2 ON goods_has_shops (shops_id);
CREATE INDEX goods_has_shops_FKIndex3 ON goods_has_shops (product_url);
CREATE INDEX goods_has_shops_FKIndex4 ON goods_has_shops (checked_last);
CREATE INDEX goods_from_persona_FKIndex1 ON goods_from_persona (goods_id);
CREATE INDEX goods_from_persona_FKIndex2 ON goods_from_persona (persona_id);
CREATE INDEX goods_has_material_FKIndex1 ON goods_has_material (goods_id);
CREATE INDEX goods_has_material_FKIndex2 ON goods_has_material (material_id);
CREATE INDEX goods_has_shop_location_FKIndex1 ON goods_has_shop_location (goods_id);
CREATE INDEX goods_has_shop_location_FKIndex2 ON goods_has_shop_location (shop_location_id);
CREATE INDEX goods_has_image_FKIndex1 ON goods_has_image (image_id);
CREATE INDEX goods_has_image_FKIndex2 ON goods_has_image (goods_id);
CREATE INDEX goods_has_image_FKIndex3 ON goods_has_image (image_goods_type_id);
CREATE INDEX goods_has_category_FKIndex1 ON goods_has_category (category_id);
CREATE INDEX goods_has_category_FKIndex2 ON goods_has_category (goods_id);
CREATE INDEX goods_has_company_FKIndex1 ON goods_has_company (company_id);
CREATE INDEX goods_has_company_FKIndex2 ON goods_has_company (goods_id);
CREATE INDEX goods_has_company_FKIndex3 ON goods_has_company (company_function_type_id);
CREATE INDEX people_create_goods_FKIndex1 ON people_create_goods (people_id);
CREATE INDEX people_create_goods_FKIndex2 ON people_create_goods (goods_id);
CREATE INDEX people_create_goods_FKIndex3 ON people_create_goods (create_type_id);
CREATE INDEX people_create_goods_FKIndex4 ON people_create_goods (people_alias_id);
CREATE INDEX goods_launch_country_FKIndex1 ON goods_launch_country(country_id);
CREATE INDEX goods_launch_country_FKIndex2 ON goods_launch_country(goods_id);
CREATE INDEX goods_launch_country_FKIndex3 ON goods_launch_country(currency_id);
CREATE INDEX goods_launch_country_FKIndex4 ON goods_launch_country(launch_date);
CREATE INDEX goods_launch_country_FKIndex5 ON goods_launch_country(launch_price);
CREATE INDEX goods_description_FKIndex1 ON goods_description (goods_id);
CREATE INDEX goods_description_FKIndex2 ON goods_description (language_id);
CREATE INDEX figure_FKIndex1 ON figure (scale_id);
CREATE INDEX figure_FKIndex2 ON figure (figure_version_id);
CREATE INDEX figure_FKIndex3 ON figure (goods_id);
CREATE INDEX goods_associated_goods_FKIndex1 ON goods_associated_goods (goods_id);
CREATE INDEX goods_associated_goods_FKIndex2 ON goods_associated_goods (another_goods_id);
CREATE INDEX goods_associated_goods_FKIndex3 ON goods_associated_goods (associated_type_id);
CREATE INDEX goods_alias_FKIndex1 ON goods_alias (goods_id);
CREATE INDEX goods_alias_FKIndex2 ON goods_alias (alias_type_id);
CREATE INDEX goods_alias_FKIndex3 ON goods_alias (language_id);
CREATE INDEX goods_alias_FKIndex4 ON goods_alias (name);